### PR TITLE
Fix for Node LTS compatibility

### LINKED ISSUE #29: [MyNoobEnv] calc.ml generate tests fail
Here is one of my stange issue : 
```
~/git/jsexplain/generator/tests$ ../../node_modules/mocha/bin/mocha calc.unlog.as.js 

  calc.ml
    1) is_empty
    ✓ push
    2) pop
    3) run
    ✓ mapMystack

  2 passing (7ms)
  3 failing
 
  1) calc.ml
       is_empty:
     TypeError: _compare_stack is not a function
      at is_empty (calc.unlog.as.js:231:11)
      at /home/sam/git/jsexplain/generator/tests/calc.unlog.as.js:313:19
      at Context.<anonymous> (calc.unlog.as.js:207:5)

  2) calc.ml
       pop:
     TypeError: expected.test is not a function
      at expectedException (assert.js:605:21)
      at innerThrows (assert.js:648:21)
      at Object.throws (assert.js:662:3)
      at Object.Mocha.assert_failwith (calc.unlog.as.js:214:44)
      at /home/sam/git/jsexplain/generator/tests/calc.unlog.as.js:328:11
      at Context.<anonymous> (calc.unlog.as.js:207:5)

  3) calc.ml
       run:
     TypeError: expected.test is not a function
      at expectedException (assert.js:605:21)
      at innerThrows (assert.js:648:21)
      at Object.throws (assert.js:662:3)
      at Object.Mocha.assert_failwith (calc.unlog.as.js:214:44)
      at /home/sam/git/jsexplain/generator/tests/calc.unlog.as.js:345:11
      at Context.<anonymous> (calc.unlog.as.js:207:5)
```
Here is a part of the code in _calc.unlog.as.js_ :
```
/* --------------------- Compare.js --------------------- */
const _compare_stack = _compare_generic;
/* --------------------- calc.unlog.js --------------------- */

var Calc = (function() {
with (Mocha) {

function C(value, stack) { return {tag: "C", value: value, stack: stack}; }

function N() { return {tag: "N" }; }

var is_empty = function (s) {
  return (_compare_stack(s, N()));
};
```
And it's true that __compare_stack_ is not a function.
Alan was passing the test this morning but i still don't understand why i have this one.
Maybe it is still my configuration which is not in place ...

### PR DESCRIPTION
**Pull request by IgnoredAmbience**
* Fix Compare.js in the generator testsuite to work with Node <9
* Travis CI should now use lts/carbon (8.x) for testing.

Fixes #29

### CODE REVIEW

**Comment by IgnoredAmbience** [comment]
@barockobamo This should fix your issue, if you could test?

**Comment by barockobamo** [comment]
I have just upgrade to Node v10 :) , i will test somewhere and give you the feedback.

**Comment by IgnoredAmbience** [comment]
Oh, the point was that we should be supporting v8, so testing on that platform would have been good. I've now managed to get the CI to use v8 of node to test it...

**Comment by IgnoredAmbience** [comment]
I remain of the opinion that we should not be bundling nodejs/npm with this repository. We should clearly state the version requirement (8+), as this is the LTS release which should be provided by most LTS linux distributions. Debian has it in stretch-backports, Ubuntu in 18.04 (16.04 is now out of support), it present in the supported releases for Fedora, but not CentOS.

In the event that the OS does not have version 8+ packaged, we should recommend that a more recent version is obtained using nvm. https://github.com/creationix/nvm

I've also just noticed that the dependencies aren't listed in the toplevel readme. I'm sure I had added them...

**Comment by barockobamo** [comment]
Ok, the problem was that i was running `make test` without `make test_init` before.
So node can stay as an external dependence.
But my test on debian with node v8.12.0 and opam 1.2.2 is KO anyway : here is how it fail :

**Comment by IgnoredAmbience** [comment]
Thanks for that bugreport. I'll take another look into it. Looks like the CI build wasn't testing the generator on each build, have now fixed that too.

**Comment by IgnoredAmbience** [comment]
It looks like this is now fixed.

**Comment by barockobamo** [comment]
Just finish the test, it's OK, (my VM is very slow, i 'am making a new one)

**Comment by IgnoredAmbience** [comment]
Yes, the test262 suite takes a long time to complete. It's not very suitable to run to completion for every change made.

**Pull request merged**
